server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript


#=============================#
#===== Database Settings =====#
#=============================#
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/one?useUnicode=true&characterEncoding=utf-8
  username: root
  password: one
  driver-class-name: com.mysql.jdbc.Driver
  druid:
    initial-size: 3
    max-active: 5
    min-idle: 2
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x' FROM DUAL